backend:
  name: github
  branch: main
  repo: moorestech/moorestech_doc
  open_authoring: true

publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: docs
    label: "Documentation"
    folder: docs
    create: true
    nested:
      depth: 20            # 必要に応じて
      summary: "{{title}}"
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }